apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: contact-ms
  template:
    metadata:
      labels:
        component: contact-ms
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: vexl-data
      containers:
        - name: contact-ms
          imagePullPolicy: Always
          image: gitlab.cleevio.cz:4567/backend/vexl/vexl-contact-ms/production:latest
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: "/var/www/static"
              name: static-files
          readinessProbe:
            httpGet:
              port: 8282
              path: /actuator/health
            initialDelaySeconds: 120
            timeoutSeconds: 20
            periodSeconds: 5
            failureThreshold: 10
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  key: spring.datasource.url
                  name: spring-profile-contact-ms
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: spring.datasource.username
                  name: spring-profile-contact-ms
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: spring.datasource.password
                  name: spring-profile-contact-ms
            - name: SECURITY_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  key: security.encryption.key
                  name: spring-profile-contact-ms
            - name: SIGNATURE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: secret.signature-public-key
                  name: spring-profile-contact-ms
            - name: AES_KEY
              valueFrom:
                secretKeyRef:
                  key: secret.aes-key
                  name: spring-profile-contact-ms
            - name: FIREBASE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: secret.firebase-client-id
                  name: spring-profile-contact-ms
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  key: secret.firebase-client-email
                  name: spring-profile-contact-ms
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: secret.firebase-private-key
                  name: spring-profile-contact-ms
            - name: FIREBASE_PRIVATE_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: secret.firebase-private-key-id
                  name: spring-profile-contact-ms
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  key: secret.firebase-project-id
                  name: spring-profile-contact-ms
            - name: FIREBASE_TOKEN_URI
              valueFrom:
                secretKeyRef:
                  key: secret.firebase-token-uri
                  name: spring-profile-contact-ms
            - name: FIREBASE_KEY
              valueFrom:
                secretKeyRef:
                  key: secret.firebase-key
                  name: spring-profile-contact-ms
            - name: FIREBASE_IOS_STORE
              valueFrom:
                secretKeyRef:
                  key: secret.firebase-ios-store
                  name: spring-profile-contact-ms
            - name: SENTRY_DNS
              valueFrom:
                secretKeyRef:
                  key: sentry.dsn
                  name: spring-profile-contact-ms