apiVersion: apps/v1
kind: Deployment
metadata:
  name: appplication-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: application
  template:
    metadata:
      labels:
        component: application
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: vexl-data
      containers:
        - name: application
          imagePullPolicy: Always
          image: gitlab.cleevio.cz:4567/backend/vexl/vexl-user-ms/devel:latest
          volumeMounts:
            - mountPath: "/var/www/static"
              name: static-files
          readinessProbe:
            httpGet:
              port: 8282
              path: /actuator/health
            initialDelaySeconds: 120
            timeoutSeconds: 20
            periodSeconds: 5
            failureThreshold: 10
          env:
            - name: TWILIO_TOKEN
              valueFrom:
                secretKeyRef:
                  key: twilio.token
                  name: spring-profile-user-ms
            - name: TWILIO_SID
              valueFrom:
                secretKeyRef:
                  key: twilio.sid
                  name: spring-profile-user-ms
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  key: spring.datasource.url
                  name: spring-profile-user-ms
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: spring.datasource.username
                  name: spring-profile-user-ms
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: spring.datasource.password
                  name: spring-profile-user-ms
            - name: SENTRY_DNS
              valueFrom:
                secretKeyRef:
                  key: sentry.dsn
                  name: spring-profile-user-ms