apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: vexl-chat-ms-api-tls
spec:
  secretName: vexl-chat-ms-api-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: chat.vexl.devel.cleevio.io
  dnsNames:
    - chat.vexl.devel.cleevio.io