package com.cleevio.vexl.module.stats.constant;

public enum StatsKey {

    ALL_TIME_COUNT,
    ACTIVE_COUNT_BUY,
    ACTIVE_COUNT_SELL,
    MODIFIED_COUNT_BUY,
    MODIFIED_COUNT_SELL,
    OFFER_PERC_5_BUY,
    OFFER_PERC_5_SELL,
    OFFER_PERC_50_BUY,
    OFFER_PERC_50_SELL,
    OFFER_PERC_95_BUY,
    OFFER_PERC_95_SELL,

    OFFERS_EXPIRED_PUBLIC_PART,
    OFFERS_EXPIRED_PRIVATE_COUNT,
    OFFERS_DELETED_PRIVATE_PARTS,
    OFFERS_DELETED_PUBLIC_PARTS,
    ;
}
