apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: offer-ms
  template:
    metadata:
      labels:
        component: offer-ms
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: vexl-data
      containers:
        - name: offer-ms
          imagePullPolicy: Always
          image: gitlab.cleevio.cz:4567/backend/vexl/vexl-offer2-ms/production:latest
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: "/var/www/static"
              name: static-files
          readinessProbe:
            httpGet:
              port: 8282
              path: /actuator/health
            initialDelaySeconds: 120
            timeoutSeconds: 20
            periodSeconds: 5
            failureThreshold: 10
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  key: spring.datasource.url
                  name: spring-profile-offer-ms
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: spring.datasource.username
                  name: spring-profile-offer-ms
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: spring.datasource.password
                  name: spring-profile-offer-ms
            - name: SECURITY_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  key: security.encryption.key
                  name: spring-profile-offer-ms
            - name: SIGNATURE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: secret.signature-public-key
                  name: spring-profile-offer-ms
            - name: AES_KEY
              valueFrom:
                secretKeyRef:
                  key: secret.aes-key
                  name: spring-profile-offer-ms
            - name: SENTRY_DNS
              valueFrom:
                secretKeyRef:
                  key: sentry.dsn
                  name: spring-profile-offer-ms