name: "[Bot] update manifests"

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'environment to update'
        required: true
        type: choice
        options:
        - prod
        - stage
        - dev

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to infrastructure repository
        env:
          INFRASTRUCTURE_REPOSITORY: ${{ secrets.infrastructure_repository}}
          INFRASTRUCTURE_REPOSITORY_TOKEN: ${{ secrets.infrastructure_repository_token}}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${INFRASTRUCTURE_REPOSITORY_TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/vexl-it/${INFRASTRUCTURE_REPOSITORY}/dispatches \
            -d '{"event_type":"${{inputs.env}}_deployment","client_payload":{"backend_image_sha":"${{github.sha}}"}}'
