name: "[Build] prod contact-ms image"

on:
  push:
    branches:
      - main
    paths:
      - "contact/**"
      - "common/**"
  workflow_dispatch:

jobs:
  build-prod-contact-ms:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::570620554963:role/github_actions_ecr_vexl
          role-session-name: GithubActionsCloudInfrastructure
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build contact-ms java
        run: gradle contact:bootJar

      - name: Build and push prod contact-ms image
        uses: docker/build-push-action@v2
        with:
          context: ./contact
          platforms: linux/amd64
          push: true
          build-args: |
            CI_PROJECT_NAME=${{ github.repository }}
            CI_COMMIT_SHORT_SHA=${{ github.sha }}
            KUBE_DOMAIN=vexl.it
            PROFILE=prod
          tags: |
            ghcr.io/${{ github.repository_owner }}/contact-ms:latest
            ghcr.io/${{ github.repository_owner }}/contact-ms:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/contact-ms:latest
            ${{ steps.login-ecr.outputs.registry }}/contact-ms:prod-${{ github.sha }}
